import { DesktopIcon, DiskCIcon, DocumentsIcon, MyComputerIcon, RecycleBinCIcon } from '../components/ui/icons';

import type { FileSystemItem } from '../store/filesystem';

export const SYSTEM_IDS = {
    ROOT: 'root',
    C_DRIVE: 'disk-c',
    DESKTOP: 'desktop-id',
    MY_COMPUTER: 'my-computer-virtual-id',
    DOCUMENTS: 'documents-id',
    USERS: 'users-id',
    USER: 'user-id',
    SYSTEM: 'rbxOS-id',
    RECYCLE: 'recycle-bin',
};

export const initialItems: Record<string, FileSystemItem> = {
    [SYSTEM_IDS.DESKTOP]: {
        id: SYSTEM_IDS.DESKTOP,
        parentId: null,
        icon: DesktopIcon,
        name: 'Área de Trabalho',
        type: 'folder',
        createdAt: Date.now(),
    },
    [SYSTEM_IDS.ROOT]: {
        id: SYSTEM_IDS.ROOT,
        parentId: SYSTEM_IDS.DESKTOP,
        name: 'Meu Computador',
        icon: MyComputerIcon,
        type: 'folder',
        createdAt: Date.now(),
    },
    [SYSTEM_IDS.C_DRIVE]: {
        id: SYSTEM_IDS.C_DRIVE,
        parentId: SYSTEM_IDS.ROOT,
        icon: DiskCIcon,
        name: 'C:',
        type: 'folder',
        createdAt: Date.now(),
    },
    [SYSTEM_IDS.USER]: {
        id: SYSTEM_IDS.USER,
        parentId: SYSTEM_IDS.C_DRIVE,
        name: localStorage.getItem('user') ?? 'User',
        type: 'folder',
        createdAt: Date.now(),
    },
    [SYSTEM_IDS.SYSTEM]: {
        id: SYSTEM_IDS.SYSTEM,
        parentId: SYSTEM_IDS.C_DRIVE,
        name: 'rbx',
        type: 'folder',
        createdAt: Date.now(),
    },
    [SYSTEM_IDS.DOCUMENTS]: {
        id: SYSTEM_IDS.DOCUMENTS,
        parentId: SYSTEM_IDS.DESKTOP,
        name: 'Meus Documentos',
        icon: DocumentsIcon,
        type: 'folder',
        createdAt: Date.now(),
    },
    [SYSTEM_IDS.RECYCLE]: {
        id: SYSTEM_IDS.RECYCLE,
        parentId: SYSTEM_IDS.DESKTOP,
        name: 'Lixeira',
        icon: RecycleBinCIcon,
        type: 'folder',
        createdAt: Date.now(),
    },

    // rbxOS folder
    // system32
    'system32-folder': {
        id: 'system32-folder',
        parentId: SYSTEM_IDS.SYSTEM,
        name: 'system32',
        type: 'folder',
        createdAt: Date.now(),
    },
    'kernel-sys': {
        id: 'kernel-sys',
        name: 'kernel',
        extension: 'sys',
        parentId: 'system32-folder',
        type: 'file',
        createdAt: Date.now(),
    },
    'windowManager-sys': {
        id: 'windowManager-sys',
        parentId: 'system32-folder',
        name: 'WindowManager',
        extension: 'sys',
        type: 'file',
        createdAt: Date.now(),
    },
    'shell32-dll': {
        parentId: 'system32-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'shell32-dll',
        name: 'shell32',
        extension: 'dll',
    },
    'desktop-sys': {
        parentId: 'system32-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'desktop-sys',
        name: 'desktop',
        extension: 'sys',
    },

    // drivers folder
    'drivers-folder': {
        parentId: SYSTEM_IDS.SYSTEM,
        type: 'folder',
        createdAt: Date.now(),
        id: 'drivers-folder',
        name: 'drivers',
    },
    'canvas-2d-drv': {
        parentId: 'drivers-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'canvas-2d-drv',
        name: 'canvas_2d',
        extension: 'drv',
    },
    'webgl-3d-drv': {
        parentId: 'drivers-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'webgl-3d-drv',
        name: 'webgl_3d',
        extension: 'drv',
    },
    'audio-drv': {
        parentId: 'drivers-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'audio-drv',
        name: 'audio',
        extension: 'drv',
    },
    // resources folder
    'resources-folder': {
        parentId: SYSTEM_IDS.SYSTEM,
        type: 'folder',
        createdAt: Date.now(),
        id: 'resources-folder',
        name: 'resources',
    },
    'icons-folder': {
        parentId: 'resources-folder',
        type: 'folder',
        createdAt: Date.now(),
        id: 'icons-folder',
        name: 'icons',
    },
    'wallpapers-folder': {
        parentId: 'resources-folder',
        type: 'folder',
        createdAt: Date.now(),
        id: 'wallpapers-folder',
        name: 'wallpapers',
    },
    'sounds-folder': {
        parentId: 'resources-folder',
        type: 'folder',
        createdAt: Date.now(),
        id: 'sounds-folder',
        name: 'sounds',
    },
    // config folder
    'config-folder': {
        parentId: SYSTEM_IDS.SYSTEM,
        type: 'folder',
        createdAt: Date.now(),
        id: 'config-folder',
        name: 'config',
    },
    'registry-json': {
        parentId: 'config-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'registry-json',
        name: 'registry',
        extension: 'json',
    },
    'profile-json': {
        parentId: 'config-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'profile-json',
        name: 'profile',
        extension: 'json',
    },
    // fonts folder
    'fonts-folder': {
        parentId: SYSTEM_IDS.SYSTEM,
        type: 'folder',
        createdAt: Date.now(),
        id: 'fonts-folder',
        name: 'fonts',
    },
    'system-font': {
        parentId: 'fonts-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'system-font',
        name: 'system_font',
        extension: 'ttf',
    },
    'shell-font': {
        parentId: 'fonts-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'shell-font',
        name: 'shell_font',
        extension: 'ttf',
    },
    // Logs folder
    'logs-folder': {
        parentId: SYSTEM_IDS.SYSTEM,
        type: 'folder',
        createdAt: Date.now(),
        id: 'logs-folder',
        name: 'logs',
    },
    'build-log': {
        parentId: 'logs-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'build-log',
        name: 'build',
        extension: 'log',
    },
    'updates-log': {
        parentId: 'logs-folder',
        type: 'file',
        createdAt: Date.now(),
        id: 'updates-log',
        name: 'updates',
        extension: 'log',
    },

    // Icons folder
    'desktop-icon': {
        id: 'desktop-icon',
        parentId: 'icons-folder',
        name: 'desktop',
        extension: 'ico',
        type: 'file',
        createdAt: Date.now(),
        content: 'src/assets/icons/desktop.webp',
    },
};
